Repository forHUFS/hufs-frontend, pull requests merged in 2021-05, with the labels that each got.

#101 [ 박수로 ] 버그픽스 : 로그인 시 로그아웃버튼으로 안바뀌는 버그
  src/components/login/Logout.js
  src/components/login/SignUp.js
  src/components/login/modals/SignInModal.js
  src/components/login/social/GoogleSignIn.js
  src/components/post/PostUpdate.js
  src/views/Header/Header.js
Labels: Status: Merge 요청

#107 [ 박수로 ] 버그픽스 : 검색결과 클릭 시 404 에러 픽스
  src/views/SearchPage/SearchPage.js
Labels: Status: Done

#115 [ 박수로 ] 버그픽스 : 회원가입 페이지
  src/components/login/modals/SignInModal.js
  src/components/login/modals/SignUpModal.js
  src/components/login/social/GoogleSignIn.js
Labels: Status: Done

#116 [ 박수로 ] 버그픽스 : 엔드포인트, 이미지 업로드
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
Labels: Status: Done

#120 [ 박수로 ] 버그픽스 : 쿼리스트링 에러 핸들링
  src/components/post/PostSearch.js
  src/components/post/SearchAll.js
  src/components/user/UserInfo.js
Labels: Status: Done

#122 [ 박수로 ] 기능수정 : 이미지 업로드 시 최대 사이즈 제한
  package.json
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
Labels: Status: Done

#123 [ 박수로 ] 버그픽스 : 공백 제목
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
Labels: Status: Done

#124 [ 박수로 ] 리팩토링 : 댓글 작성, 추천 등 기능시 성능개선
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostView.js
Labels: Status: Done

#129 [ 박수로 ] 버그픽스 : 스크랩 흰 화면
  src/components/user/UserInfo.js
  src/components/user/UserScrap.js
Labels: Status: Done

#131 [ 박수로 ] 버그픽스 : 공백 댓글
  src/components/comment/CommentEdit.js
Labels: Status: Done

#132 [ 박수로 ] 기능수정 : 게시글 번호 인덱스 출력
  src/components/post/PostList.js
Labels: Status: Done

#136 [ 박수로 ] 버그픽스 : 닉네임, 웹메일 에러 핸들링
  src/components/login/modals/SignUpModal.js
Labels: HotFix

#137 [ 박수로 ] 기타 : 스웨거 변경에 따른 변수명 수정
  src/components/post/PostList.js
Labels: Status: Done

#141 [ 박수로 ] 기능추가 : 댓글 추천, 삭제, 신고
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
  src/components/post/ReportModal.js
Labels: Status: Done

#151 [ 이태훈 ] 기능추가 : 지도 부분 목록 보이기,감추기
  src/components/map/mapSection/Card.js
  src/components/map/mapSection/MapContainer.js
  src/components/post/PostList.js
  src/components/user/UserComment.js
  src/components/user/UserPost.js
  src/components/user/UserScrap.js
  src/css/Map.css
Labels: Status: Merge 요청, Status: 리뷰 요청

#153 [ 박수로 ] 버그픽스 : 장학금 달력 컴포넌트
  src/_actions/post_action.js
  src/_actions/user_action.js
  src/components/calendar/CalendarComponent.js
  src/components/calendar/CalendarMainPage.js
  src/components/post/PostList.js
  src/components/post/PostSearch.js
  src/components/post/PostView.js
  src/components/post/SearchAll.js
  src/components/user/UserInfo.js
  src/views/CalendarPage/CalendarPage.js
  src/views/MyPage/MyPage.js
  src/views/SearchPage/SearchPage.js
Labels: HotFix

#152 [ 황남주 ] 기능 추가 : 상점 평점, 리뷰 개수, 게시글 삭제
  src/_actions/reviewPost_action.js
  src/_actions/types.js
  src/_reducer/review_reducer.js
  src/components/map/mapSection/Card.js
  src/components/map/mapSection/mapData/star.png
  src/components/map/reviewSection/newReviewSection/ReviewList.js
  src/components/map/reviewSection/newReviewSection/ReviewUpdate.js
  src/views/MapPage/MapPage.js
  src/views/ReviewPage/ReviewPage.js
Labels: Status: Merge 요청

#154 [ 박수로 ] 기능추가 : 대댓글 기본 기능
  src/components/comment/CommentList.js
Labels: Status: Merge 요청

#155 [ 이태훈 ] 이용약관, 개인정보 취급방침 작성 ,적용
  src/components/login/modals/SignUpModal.js
  src/components/rule/InformationModal.js
  src/components/rule/Rule.js
  src/components/rule/UseModal.js
  src/css/Rule.css
  src/views/Footer/Footer.js
Labels: Status: Done

#158 [ 박수로 ] 버그픽스 : 대댓글 parentId
  src/components/comment/CommentList.js
Labels: HotFix

#159 [ 박수로 ] 에러픽스 : 대댓글 관련
  src/components/comment/CommentList.js
Labels: HotFix

#160 [ 박수로 ] 기능추가 : 캘린더 필터, favicon
  public/favicon.ico
  public/index.html
  src/App.js
  src/_actions/user_action.js
  src/components/calendar/CalendarComponent.js
  src/hoc/auth.js
  src/views/Header/Header.js
  src/views/PostPage/Post.js
Labels: Status: Done

#161 [ 박수로 ] 기능 수정 : 캘린더 get -> post
  src/_actions/calender_action.js
  src/components/calendar/CalendarComponent.js
Labels: HotFix

#164 [ 박수로 ] 기능수정 : card get요청
  src/components/map/mapSection/Card.js
Labels: Status: Done

#163 [ 노가영 ] 기능 수정 : 필수 항목 변경 및 동의하기 버튼 수정
  src/components/login/modals/SignUpModal.js
Labels: Status: Merge 요청, Status: 리뷰 요청

#167 [ 이태훈 ] 내부게시판 검색 값 수정
  src/components/post/PostList.js
  src/components/post/PostSearch.js
  src/components/post/PostSub.js
  src/views/SearchPage/SearchPage.js
Labels: Status: Done, Status: Merge 요청

#166 [ 황남주 ] 기능 수정 : 지도 검색, 평점 null값 수정
  src/components/map/mapSection/Card.js
  src/components/map/mapSection/MapContainer.js
  src/components/map/reviewSection/newReviewSection/ReviewList.js
  src/components/map/reviewSection/newReviewSection/ReviewUpdate.js
Labels: Status: Done

#168 [ 박수로 ] 기능변경 : 캘린더 필터, 기본값
  package.json
  src/components/calendar/CalendarComponent.js
  src/components/calendar/CalendarMainPage.js
Labels: HotFix, Status: Done

#179 [ 박수로 ] 에러픽스 : 마이페이지 웹메일, 로그아웃 렌더링
  src/components/user/UserInfo.js
  src/views/Header/Header.js
Labels: HotFix

#180 [ 박수로 ] 버그픽스 : 로그아웃 라우팅,
  src/components/login/Logout.js
  src/components/user/UserInfo.js
Labels: HotFix

#183 [ 박수로 ] 핫픽스 : 닉네임 수정 에러핸들링
  src/components/user/UserInfo.js
Labels: HotFix

#188 [ 박수로 ] 에러픽스 : 중복 웹메일 에러 핸들링
  src/components/user/UserInfo.js
Labels: HotFix

#189 [ 박수로 ] 에러픽스 : 중복 웹메일 response 에러 핸들링
  src/components/user/UserInfo.js
Labels: HotFix

#187 [ 황남주 ] 버그 픽스 : 리뷰 페이지 일부 안보임 수정
  src/components/map/mapSection/Card.js
  src/views/MapPage/MapPage.js
Labels: HotFix

#190 [노가영] 기능 수정 : 웹메일로 회원가입시 자동으로 웹메일 저장
  src/components/login/modals/SignUpModal.js
Labels: Status: Merge 요청
