Repository forHUFS/hufs-frontend, pull requests merged in 2021-06, with the labels that each got.

#197 [ 박수로 ] 리팩토링 : user관련 redux 모두 제거 후 useSWR, axios로 대체
  src/App.js
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_actions/user_action.js
  src/components/calendar/CalendarMainPage.js
  src/components/calendar/CalendarP.js
  src/components/login/Logout.js
  src/components/post/PostSearch.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/components/post/SearchAll.js
  src/components/user/UserInfo.js
  src/components/user/UserWithdraw.js
  src/functions/errorHandling.js
  src/hooks/useEmailAuth.js
  src/hooks/usePostDetail.js
  src/views/DocumentPage/DocumentPage.js
  src/views/EmailAuthPage/EmailAuthPage.js
  src/views/Header/Header.js
  src/views/MajorPage/MajorPage.js
  src/views/MyPage/MyPage.js
Labels: Status: Done

#203 [ 박수로 ] 리팩토링 : post,calendar, comment, user 관련 redux 모두 제거 후 useSWR 대체
  src/_actions/calender_action.js
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_reducer/calendar_reducer.js
  src/_reducer/comment_reducer.js
  src/_reducer/index.js
  src/_reducer/post_reducer.js
  src/_reducer/user_reducer.js
  src/components/calendar/CalendarComponent.js
  src/components/calendar/CalendarMainPage.js
  src/components/calendar/CalendarP.js
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostSearch.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/components/post/SearchAll.js
  src/components/user/UserScrap.js
  src/functions/commentFunctions.js
  src/functions/postFunctions.js
  src/hooks/useScrap.js
  src/views/CalendarPage/CalendarPage.js
  src/views/Header/Header.js
  src/views/SearchPage/SearchPage.js
Labels: Status: Done, Status: Merge 요청

#205 [ 이태훈 ] 리뷰 리팩토링
  src/components/map/house/House.js
  src/components/map/mapSection/Card.js
  src/components/map/mapSection/MapContainer.js
  src/components/map/reviewSection/newReviewSection/ReviewHead.js
  src/components/map/reviewSection/newReviewSection/ReviewList.js
  src/components/map/reviewSection/newReviewSection/ReviewView.js
  src/views/MapPage/MapPage.js
  src/views/ReviewPage/ReviewPage.js
Labels: Status: Done

#210 [ 박수로 ] 에러픽스 : useSWR 에러 핸들링 관련 핫픽스
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/functions/errorHandling.js
  src/hoc/auth.js
  src/hooks/useBoard.js
  src/hooks/useUserInfo.js
  src/index.js
  src/views/MyPage/MyPage.js
Labels: HotFix

#214 [ 박수로 ] 리팩토링 : 에러핸들링 통합 후 useErrorHandling 훅으로 리팩토링
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/functions/errorHandling.js
  src/functions/postFunctions.js
  src/hooks/useBoard.js
  src/hooks/useErrorHandling.js
  src/hooks/useUserInfo.js
  src/views/MyPage/MyPage.js
Labels: Status: Merge 요청

#215 [ 박수로 ] 버그픽스 : 마이페이지 헤더 중복
  src/views/MyPage/MyPage.js
Labels: HotFix
