Repository forHUFS/hufs-frontend, pull requests merged in 2021-07, with the labels that each got.

#217 [ 박수로 ] 기능수정 : 댓글, 대댓글 default 값 변경
  src/components/comment/CommentList.js
  src/components/post/PostSearch.js
Labels: Status: Merge 요청

#218 [ 박수로 ] 에러픽스 : 댓글 작성 엔드포인트 변경
  src/functions/commentFunctions.js
Labels: HotFix

#219 [ 박수로 ] 기능 수정 : 댓글 삭제 시 내용 변경
  src/components/comment/CommentList.js
Labels: Status: Merge 요청

#220 [ 박수로 ] 리팩토링 : 엔드포인트 리팩토링
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/functions/commentFunctions.js
  src/functions/postFunctions.js
  src/views/MapPage/Mapdetail/ReviewEdit.js
  src/views/MapPage/Mapdetail/ReviewUpdate.js
Labels: Status: Merge 요청

#221 [ 박수로 ] 기능추가 : responsive 훅 추가 및 LandingPage, header 반응형 작업
  .github/workflows/main.yml
  package.json
  src/App.js
  src/components/calendar/CalendarList.js
  src/components/menubox/HeaderMenu.js
  src/components/post/SearchAll.js
  src/hooks/useResponsive.js
  src/views/Common/Header.js
  src/views/Common/Quick.js
  src/views/LandingPage/LandingPage.js
Labels: Status: Merge 요청

#223 [ 황남주 ] 기능추가 / 리팩토링 : 취/창업공간,엔드포인트 수정
  src/App.js
  src/_actions/reviewPost_action.js
  src/components/career/CareerInterview.js
  src/components/career/CareerNavi.js
  src/components/career/CareerQuestion.js
  src/components/career/CareerReview.js
  src/components/career/CareerReviewWrite.js
  src/components/map/mapSection/MapContainer.js
  src/components/map/mapSection/MoreRank.js
  src/components/map/mapSection/RecentReview.js
  src/css/Career.css
  src/views/CareerPage/CareerPage.js
  src/views/MapPage/Mapdetail/ReviewEdit.js
  src/views/MapPage/Mapdetail/ReviewUpdate.js
Labels: Status: Merge 요청

#224 [ 박수로 ] 에러픽스 : 병합 에러
  src/components/career/CareerReviewWrite.js
  src/components/menubox/HeaderMenu.js
  src/components/post/SearchAll.js
  src/functions/postFunctions.js
  src/hooks/useResponsive.js
  src/views/Common/Quick.js
  src/views/LandingPage/LandingPage.js
  src/views/MapPage/Mapdetail/ReviewEdit.js
  src/views/MapPage/Mapdetail/ReviewUpdate.js
Labels: HotFix

#226 [ 박수로 ] 기능추가 : PostList 모바일 반응형
  src/components/calendar/CalendarList.js
  src/components/menubox/HeaderMenu.js
  src/components/post/PostList.js
  src/components/post/SearchAll.js
  src/hooks/useResponsive.js
  src/views/Common/Quick.js
  src/views/LandingPage/LandingPage.js
Labels: Status: Done

#227 [ 박수로 ] 에러픽스 : 검색 관련 에러 수정
  src/App.js
  src/components/post/PostSearch.js
  src/components/post/PostSub.js
  src/components/post/ReportModal.js
  src/components/post/SearchAll.js
  src/functions/postFunctions.js
  src/hooks/useBoard.js
  src/views/PostPage/Post.js
  src/views/SearchPage/SearchPage.js
Labels: Status: Done

#229 [ 박수로 ] 기능추가 : 게시글 ,게시판, 댓글, 대댓글 모바일 반응형 작업
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostView.js
  src/components/post/SearchAll.js
  src/hooks/useResponsive.js
  src/views/PostPage/Post.js
Labels: Status: Done

#231 [ 박수로 ] 기능추가 : 전공 게시판 추가
  src/App.js
  src/components/MajorCard.js
  src/components/comment/CommentEdit.js
  src/components/menubox/HeaderMenu.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostSub.js
  src/components/post/PostView.js
  src/css/App2.css
  src/css/Post.css
  src/hooks/useErrorHandling.js
  src/hooks/useMainMajor.js
  src/views/MajorPage/MajorBoard.js
  src/views/MajorPage/MajorList.js
  src/views/MajorPage/MajorPage.js
  src/views/PostPage/Post.js
Labels: Status: Done

#233 [ 박수로 ] 기능추가 : 전공 게시판 글 작성 제한
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/hoc/majorAuth.js
  src/hooks/useUserInfo.js
  src/views/PostPage/Post.js
Labels: Status: Done

#234 기능수정 : boardTitle 변경
  src/App.js
  src/components/menubox/HeaderMenu.js
  src/components/post/PostEdit.js
Labels: HotFix, Status: Done

#235 [ 박수로 ] 전공게시판 작성, 수정 유효성 검사
  src/components/menubox/HeaderMenu.js
  src/components/post/PostEdit.js
  src/components/post/PostHeaderToolBar.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/user/MajorSelect.js
  src/components/user/UserInfo.js
  src/components/user/UserScrap.js
  src/functions/postFunctions.js
  src/hooks/useMajorCheck.js
  src/views/MyPage/MyPage.js
Labels: Status: Merge 요청

#236 [ 황남주 ] 기능수정 : boardTitle 수정 및 반응형
  src/App.js
  src/components/map/MapNavi.js
  src/components/map/mapSection/KakaoMap.js
  src/components/map/mapSection/MapContainer.js
  src/components/map/mapSection/Rank.js
  src/components/map/reviewSection/newReviewSection/ReviewHead.js
  src/components/map/reviewSection/newReviewSection/ReviewList.js
  src/components/menubox/HeaderMenu.js
Labels: Status: Merge 요청

#237 [ 노가영 ] 기능 수정 : 회원가입 캠퍼스 구분 및 검색 가능
  src/App.js
  src/components/login/SignUp.js
  src/components/login/SignUpForm.js
  src/components/login/modals/SignInModal.js
  src/components/login/modals/SignUpModal.js
  src/components/login/social/GoogleSignIn.js
  src/components/login/social/KakaoSignIn.js
  src/components/login/style/google_pic.png
  src/components/login/style/kakao_pic.png
  src/hooks/useDoubleMajor.js
  src/views/RegisterPage/SignInPage.js
  src/views/RegisterPage/SignUpPage.js
Labels: Status: Done

#238 [ 박수로 ] 기능추가 : 장학금 페이지 모바일 반응형
  src/components/post/SearchAll.js
  src/css/PostView.module.css
  src/hooks/useResponsive.js
  src/views/CalendarPage/CalendarPage.js
Labels: Status: Done

#244 [ 이태훈 ] SEO태그 , Open Graph 적용
  a
  public/index.html
  src/components/login/social/GoogleSignIn.js
  src/components/menubox/HeaderMenu.js
Labels: Status: Done, Status: Merge 요청

#245 [ 박수로 ] 기능 수정 : 세부 전공 제거 및 전공 정리
  src/components/MajorCard.js
  src/components/login/social/GoogleSignIn.js
  src/components/post/PostEdit.js
  src/components/post/PostSearch.js
  src/components/user/UserScrap.js
  src/hooks/useMajorCheck.js
  src/views/MajorPage/MajorBoard.js
  src/views/MajorPage/MajorList.js
  src/views/MajorPage/MajorPage.js
  src/views/MajorPage/majorCategory.json
Labels: Status: Done

#247 [ 노가영 ] 기능 추가 : 졸업생 인증
  src/components/user/Graduate.js
  src/components/user/MajorSelect.js
  src/components/user/SecondMajorSelect.js
  src/css/Graduate.module.css
  src/views/MyPage/MyPage.js
Labels: Status: Done

#250 [ 황남주 ] 기능 수정 : 취창업공간 서버 연동
  src/App.js
  src/_actions/reviewPost_action.js
  src/components/career/CareerNavi.js
  src/components/career/CareerQuestion/CareerQuestion.js
  src/components/career/CareerQuestion/CareerQuestionView.js
  src/components/career/CareerQuestion/CareerQuestionWrite.js
  src/components/career/CareerReview/CareerReview.js
  src/components/career/CareerReview/CareerReviewView.js
  src/components/career/CareerReview/CareerReviewWrite.js
  src/components/menubox/HeaderMenu.js
  src/functions/postFunctions.js
  src/views/CareerPage/CareerPage.js
Labels: Status: Done

#259 [ 박수로 ] 기능 수정 : 전공 엔드포인트 변경 및 전공관련 커스텀 훅 추가
  src/components/login/SignUpForm.js
  src/components/login/social/KakaoSignIn.js
  src/components/menubox/HeaderMenu.js
  src/components/user/Graduate.js
  src/components/user/UserInfo.js
  src/functions/postFunctions.js
  src/hooks/useErrorHandling.js
  src/hooks/useMajor.js
  src/hooks/useUserInfo.js
  src/views/LandingPage/LandingPage.js
Labels: Status: Done
