Repository forHUFS/hufs-frontend, pull requests merged in 2021-03, with the labels that each got.

#1 [ 박수로 ] 기능추가: 게시글 관련 기능
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/comment_reducer.js
  src/_reducer/index.js
  src/_reducer/post_reducer.js
  src/_reducer/user_reducer.js
  src/components/Post/Post.js
  src/components/Post/PostList.css
  src/components/Post/PostList.js
  src/components/Post/PostView.js
  src/components/Post/list_action.js
  src/components/Post/test.js
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.css
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/hooks/useInput.js
  src/index.js
  src/views/Footer/Footer.js
  src/views/Header/Header.js
  src/views/LandingPage/LandingPage.js
  src/views/PostPage/Post.js
Labels: Status: 리뷰 요청

#3 [ 박수로 ] 기능 추가: 이미지 업로드 기능
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_reducer/post_reducer.js
  src/components/Post/PostList.css
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/hooks/useInput.js
  src/views/LandingPage/LandingPage.js
Labels: Status: Merge 요청

#4 [이태훈] 검색기능
  src/components/search/App3.js
  src/components/search/ContentTable.js
  src/components/search/Search.js
Labels: Status: Merge 요청, Status: 리뷰 요청

#5 [ 박수로 ] 버그 픽스 : 이미지 src 추출 기능
  .gitignore
  src/App.js
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
Labels: Status: Merge 요청

#6 [ 박수로 ] 기능추가 : HOC 인가 기능
  src/App.js
  src/_actions/user_action.js
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
  src/hoc/auth.js
Labels: Status: Merge 요청

#7 [ 박수로 ] 기능추가 : 게시글, 댓글 액션 에러 핸들링
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_reducer/comment_reducer.js
  src/_reducer/post_reducer.js
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/views/LandingPage/LandingPage.js
Labels: Status: Merge 요청

#8 [ 박수로 ] 기능추가 : 마이페이지 상태관리
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/index.js
  src/_reducer/post_reducer.js
  src/_reducer/user_reducer.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/user/UserComment.js
  src/components/user/UserInfo.js
  src/components/user/UserPost.js
  src/components/user/UserScrap.js
  src/components/user/UserWithdrawl.js
  src/index.js
  src/views/MyPage/MyPage.js
Labels: Status: Merge 요청

#9 [ 박수로 ] 기능삭제 : 중복 기능 삭제
  src/_reducer/post_reducer.js
  src/_reducer/user_reducer.js
  src/components/post/PostList.js
  src/components/user/UserComment.js
  src/components/user/UserInfo.js
  src/components/user/UserPost.js
  src/components/user/UserScrap.js
  src/components/user/UserWithdrawl.js
  src/views/MyPage/MyPage.js
Labels: Status: Merge 요청

#11 [ 박수로 ] 기능추가: 기본 로그인 폼
  src/App.js
  src/components/login/GoogleLogin.js
  src/components/login/KakaoLogin.js
  src/components/login/LoginForm.js
  src/components/login/ShowButton.js
  src/components/login/kakao_pic.png
  src/views/LoginPage/LoginPage.js
Labels: Status: Merge 요청

#12 [ 박수로 ] 기능추가 : 마이페이지 닉네임 변경
  package-lock.json
  package.json
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/user_reducer.js
  src/components/user/MajorSelect.js
  src/components/user/SecondMajorSelect.js
  src/components/user/UserComment.js
  src/components/user/UserInfo.js
  src/components/user/UserWithdrawl.js
  src/views/MyPage/MyPage.js
Labels: Status: Merge 요청

#17 [ 리팩토링 ] 박수로 : url 수정
  src/App.js
  src/_actions/calender_action.js
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/comment_reducer.js
  src/_reducer/post_reducer.js
  src/_reducer/user_reducer.js
  src/components/comment/CommentList.js
  src/components/login/LoginForm.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/user/MajorSelect.js
  src/components/user/SecondMajorSelect.js
  src/components/user/UserInfo.js
  src/components/user/UserScrap.js
  src/components/user/UserWithdraw.js
  src/views/LoginPage/LoginPage.js
  src/views/MyPage/MyPage.js
  src/views/PostPage/Post.js
Labels: Status: Done

#19 [ 리팩토링 ] 박수로 : api request, response 정리
  src/_actions/calender_action.js
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/comment_reducer.js
  src/_reducer/post_reducer.js
  src/_reducer/user_reducer.js
  src/components/calendar/CalendarComponent.js
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/user/UserInfo.js
Labels: Status: Done

#20 [이태훈] 슬라이드 배너해결,css추가 수정 리팩토리 해놈
  package.json
  src/App.css
  src/banner/banner1.png
  src/banner/banner2.png
  src/banner/banner3.png
  src/banner/banner4.png
  src/components/slide/Slide.css
  src/components/slide/Slide.js
  src/views/Footer/Footer.js
  src/views/Header/Header.js
  src/views/LandingPage/LandingPage.js
  src/views/Quick/Quick.js
Labels: Status: Done, Status: 리뷰 요청

#22 [ 박수로 ] 리팩토링 : API 테스트 후 status 핸들링
  .gitignore
  src/App.js
  src/_actions/calender_action.js
  src/_actions/comment_action.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/calendar_reducer.js
  src/_reducer/index.js
  src/_reducer/post_reducer.js
  src/components/calendar/CalendarComponent.js
  src/components/comment/CommentEdit.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.css
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/components/user/MajorSelect.js
  src/components/user/SecondMajorSelect.js
  src/components/user/UserComment.js
  src/components/user/UserInfo.js
  src/components/user/UserPost.js
  src/components/user/UserScrap.js
  src/components/user/UserWithdraw.js
  src/views/CalendarPage/CalendarPage.js
  src/views/MyPage/MyPage.js
Labels: Status: Merge 요청

#23 [ 박수로 ] 리팩토링 : 404 페이지 및 에러 응답 핸들링
  src/App.js
  src/_actions/post_action.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostView.js
  src/components/post/ReportModal.js
  src/views/CalendarPage/CalendarPage.js
  src/views/LandingPage/LandingPage.js
  src/views/MyPage/MyPage.js
  src/views/Page404/Page404.js
  src/views/Quick/Quick.js
Labels: Status: Done

#25 [ 박수로 ] 기능추가 : 이메일 인증 응답에 따른 페이지 작성
  package.json
  src/App.js
  src/_actions/post_action.js
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/user_reducer.js
  src/components/calendar/CalendarComponent.js
  src/components/comment/CommentList.js
  src/components/post/PostEdit.js
  src/components/post/PostList.js
  src/components/post/PostUpdate.js
  src/components/post/PostView.js
  src/components/user/UserInfo.js
  src/components/webmail/AuthAlready.js
  src/components/webmail/AuthExpired.js
  src/components/webmail/AuthSuccess.js
  src/views/EmailAuthPage/EmailAuthPage.js
  src/views/Page404/Page404.js
Labels: Status: Done

#26 [ 박수로 ] 기능추가 : 메인 페이지 작은 캘린더
  src/App.css
  src/App.js
  src/components/calendar/CalendarComponent.js
  src/components/calendar/CalendarMainPage.js
Labels: Status: Done

#29 [ 노가영 ] 기능 수정: 로그인 -> 회원가입 연결
  src/components/login/GoogleLogin.js
  src/components/login/KakaoLogin.js
  src/components/login/SIgnUp.js
  src/components/login/ShowButton.js
  src/components/login/modals/signInModal.js
  src/components/login/modals/signUpModal.js
  src/components/login/style/kakao_pic.png
Labels: Status: Done

#32 [ 박수로 ] 기능추가 : 로그아웃 기능
  src/App.css
  src/App2.css
  src/_actions/types.js
  src/_actions/user_action.js
  src/_reducer/user_reducer.js
  src/components/calendar/CalendarMainPage.js
  src/components/login/Logout.js
  src/views/Header/Header.js
Labels: Status: Done

#39 [ 황남주 ] 기능 수정 : 지도 전체적인 CSS 수정
  src/_actions/reviewPost_action.js
  src/components/map/exampleInfo/icon1.png
  src/components/map/exampleInfo/icon2.png
  src/components/map/mapSection/Card.css
  src/components/map/mapSection/Card.js
  src/components/map/mapSection/KakaoMap.js
  src/components/map/mapSection/MapContainer.js
  src/components/map/mapSection/icon_rstrn.png
  src/components/map/reviewSection/ItemList.js
  src/components/map/reviewSection/ItemModifyForm.js
  src/components/map/reviewSection/ItemRead.js
  src/components/map/reviewSection/ItemRegisterForm.js
  src/components/map/reviewSection/ReviewEx.json
  src/components/map/reviewSection/Reviewdata1.json
  src/components/map/reviewSection/reviewContainer/ItemListContainer.js
  src/components/map/reviewSection/reviewContainer/ItemModifyContainer.js
  src/components/map/reviewSection/reviewContainer/ItemReadContainer.js
  src/components/map/reviewSection/reviewContainer/ItemRegisterContainer.js
  src/views/MapInforPage/MapInforPage.js
  src/views/MapPage/MapPage.js
  src/views/ReviewPage/ReviewPage.js
Labels: Status: Done

#38 [ 이태현 ] 기능 추가: Login 관련 기능 추가
  package.json
  src/components/login/modals/SignInModal.js
  src/components/login/modals/SignUpModal.js
  src/config.js
Labels: Status: 리뷰 요청

#45 [ 박수로 ] 버그픽스 : 코드 중복 제거
  src/components/login/modals/SignUpModal.js
  src/components/map/mapSection/Card.js
  src/components/map/mapSection/MapContainer.js
  src/views/MapPage/MapPage.js
Labels: Status: Done
